name: Release
on:
    push:
        tags: ["v*"]

jobs:
    release:
        uses: commitspark/graphql-api/.github/workflows/npm-publish.yaml@main
        permissions:
            contents: read
            id-token: write
